In [2]:
import numpy as np
import tensorflow as tf


c:\Users\vic\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


**Simple Batching**

In [7]:
inc_dataset = tf.data.Dataset.range(100)
dec_dataset = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))
batched_dataset = dataset.batch(4, drop_remainder=True)

it = iter(batched_dataset)
for batch in batched_dataset.take(10):
    print([arr.numpy() for arr in batch])

batched_dataset

[array([0, 1, 2, 3], dtype=int64), array([ 0, -1, -2, -3], dtype=int64)]
[array([4, 5, 6, 7], dtype=int64), array([-4, -5, -6, -7], dtype=int64)]
[array([ 8,  9, 10, 11], dtype=int64), array([ -8,  -9, -10, -11], dtype=int64)]
[array([12, 13, 14, 15], dtype=int64), array([-12, -13, -14, -15], dtype=int64)]
[array([16, 17, 18, 19], dtype=int64), array([-16, -17, -18, -19], dtype=int64)]
[array([20, 21, 22, 23], dtype=int64), array([-20, -21, -22, -23], dtype=int64)]
[array([24, 25, 26, 27], dtype=int64), array([-24, -25, -26, -27], dtype=int64)]
[array([28, 29, 30, 31], dtype=int64), array([-28, -29, -30, -31], dtype=int64)]
[array([32, 33, 34, 35], dtype=int64), array([-32, -33, -34, -35], dtype=int64)]
[array([36, 37, 38, 39], dtype=int64), array([-36, -37, -38, -39], dtype=int64)]


<_BatchDataset element_spec=(TensorSpec(shape=(4,), dtype=tf.int64, name=None), TensorSpec(shape=(4,), dtype=tf.int64, name=None))>

In [8]:
# Batching tensors with padding
dataset = tf.data.Dataset.range(100)
dataset = dataset.map(lambda x: tf.fill([tf.cast(x,tf.int32)], x))
dataset = dataset.padded_batch(4, padded_shapes=(None,))

for batch in dataset.take(2):
    print(batch.numpy())
    

[[0 0 0]
 [1 0 0]
 [2 2 0]
 [3 3 3]]
[[4 4 4 4 0 0 0]
 [5 5 5 5 5 0 0]
 [6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]]


In [ ]:
# Processing multiple epochs with Dataset.repeat()

....

plot_batch_sizes(batches)